LIBNAME JONY '/home/u63480479/my_shared_file_links/U63480479';

DATA DADOS_LEFTJOIN;
INPUT ID NOME $;
DATALINES;
1 CORDAO
1 VIDEOGAME
10 CARTAO CREDITO
8 SALGADO
7 CELULAR
1 NOTEBOOK
;
RUN;





PROC SQL;
	CREATE TABLE IFNULL AS SELECT 
		A.NOME
		,COALESCE(B.NOME, 'NAO COMPROU PRODUTOS') AS NOME_PRODUTOCOMPRADO
	FROM JONY.DADOS_PRONTOS AS A LEFT JOIN
	DADOS_LEFTJOIN AS B ON A.ID = B.ID
;
QUIT;