LIBNAME JONY '/home/u63480479/my_shared_file_links/u63480479';

%MACRO MACRO_TRATAMENTO(INICIO, FIM);
	%DO I = &INICIO. %TO &FIM.;
		%LET NOME_BASE = JUNCAO_&I.;
		%LET FR = BASE_ANALISE_&I.;
		PROC SQL;
			CREATE TABLE &NOME_BASE. AS SELECT
				A.ID
				,CANAL
				,B.VALORES_PAGO/A.VALORES_ORIGINAL AS CALC
			FROM JONY.&FR. AS A
			LEFT JOIN JONY.DADOS_INPUT AS B ON A.ID = B.ID
			;
		QUIT;
	%END;
%MEND;

%MACRO_TRATAMENTO(202309, 202310);


