DATA NOMES_DADOS;
SET;
	FORMAT NOME $30.;

	NOME = 'JONATHAN/ALVES '
;
RUN;

DATA DADOS_NOMES;
SET NOMES_DADOS;
/* PEGA O SEGUNDO ITEM DA LISTA DE ITENS0 QUE CRIAMOS 	
	EXEMPLO: JONATHAN_ALVES_NOGUEIRA
COM O SCAN EU FAÇO UMA LISTA DE ITENS [JONATHAN, ALVES, NOGUEIRA] 
PASSO O SEGUNDO PARAMETRO PARA PEGAR O ALVES
*/
segundo_nome = SCAN(NOME,2,"/");
RUN;
DATA NOMES_DADS;
INPUT NOME $;
DATALINES;
JONATHAN_ALVES_NOGUEIRA
;
RUN;

DATA DADOS_NOMS;
SET NOMES_DADOS;
segundo_nome = SCAN(NOME, 2, "_");
RUN;
